сделал базу данных станций
Vasha-reclama/GroupLab pull request #3
Opened 2024-05-10 22:14 UTC by VladislavLinyaev

2024-05-11 06:50 UTC, silverwolf0070 requested changes
Не корректная реализация, в первую очередь непонятно почему все функции для работы с таблицей объявлены внутри класса, внутри класса не должно быть динамической памяти по типу std::vector

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	//void removeStation(int stationId);  //����� ��� ����� 2 ��� �������?? ��� ����������� ������ Station?
Эти функции нужны для работы класса маршрутов, тк маршрут - это последовательность станций

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	std::vector<Station> adjacent_stations;  // ��� ������� �������
это не должно быть в классе станций
Класс - это один объект, он не должен содержать в себе описание множества одних и тех же объектов.
Смежные станции для одной конкретной станции - это последовательность id этих самых смежных станций (в миро это было указано)

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	char* getName();
возвращаемое значение лучше сделать как string, при return не будет никакой проблемы, а с std::string работать куда проще

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	int getDistance();
Возвращаемое значение должно быть int*

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	void removeAdjacentStation(int stationId, int adjacentId);
Достаточно передать только id смежных станций

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	//void editAdjacentStation(int stationId, int adjacentId, char* name, int newDistance);
функция необходима для изменения последовательности станций

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	Station* getStation(int stationId);
возвращаемое значение должно быть int, тк хранить внутри класса другой класс очень ресурсозатратно, поэтому и используем id

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	void findStation(char* name);
Все эти функции должны быть прописаны вне класса, иначе в одном классе будут происходить страшные вещи, а объём одного объекта в памяти будет расти экспоненциально

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/Source.cpp
Для проверки можно было просто вызывать функции, но ладно

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/Station_management.cpp
Этот файл нужен, тк если все писать в station.cpp то можно слишком легко запутаться в коде, да и редактировать его в дальнейшем будет не удобно

2024-05-11 06:50 UTC, silverwolf0070 commented on GroupLab/Station.cpp
В целом непонятно, что вообще происходит здесь. Все функции для работы с таблицей должны быть отделены от класса, std::vector<Station> stations должен создаваться в мейне, и быть аргументом для этих функций, которые должны быть в пространстве имен rjd. Для примера можешь посмотреть, как сейчас это сделано в master ветке для Route

2024-05-11 09:00 UTC, VladislavLinyaev commented on GroupLab/RusRails.h
> +	//void removeStation(int stationId);  //����� ��� ����� 2 ��� �������?? ��� ����������� ������ Station?
проект не собирался , я их закоментил на время

2024-05-13 12:20 UTC, silverwolf0070 requested changes
Во первых, куда подевались массивы со смежными станциями?
Во вторых, все функции для управления бд должны быть отдельными функциями в rjd

2024-05-13 12:20 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	std::string name; // ��� �������
Имя станции мы храним как массив чаров, иначе используется динамическая память и при сохранении мы не знаем четкий размер файла

2024-05-13 12:20 UTC, silverwolf0070 commented on GroupLab/RusRails.h
Станция может быть связана со множеством других станций(максимум 5), следовательно нам нужно два интовых массива длинной в 5 едениц, в одном храним все id связанных станций с этой, в другом массиве расстояние до этих станций на соотвествующих позициях

2024-05-13 12:20 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +class StationManager {
ЗАЧЕМ ЭТО ЗДЕСЬ???????????? Нам не нужны лишние классы, делаем все в одном стиле, это надо было раньше обсуждать, сейчас делаем отдельными функциями без класса

2024-05-13 12:20 UTC, silverwolf0070 commented on GroupLab/RusRails.h
> +	int getSize(); // ������� �������
Это все должно быть отдельными функциями

2024-05-18 12:22 UTC, silverwolf0070 approved these changes

2024-05-18 12:22 UTC, silverwolf0070 commented on GroupLab/Station.cpp
>  }
Надо вывод сделать в одну строчку, ну ладно, пойдет, я потом переделаю, когда буду делать мейн

2024-05-18 12:26 UTC, merged